[package]
name = "simai"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.4"
chumsky = "0.10.1"
fraction = "0.15.3"

[dev-dependencies]
insta = { version = "1.46.3", features = ["glob"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
